### ISSUE TITLE
Ensure to pass SHA-384 param and fetch verification method early to get key size

### ISSUE THREAD

**Issue by dlongley** [w3c/vc-di-ecdsa#32]
We need to ensure that SHA-384 is passed as a param / used as a hash in RDFC-1 and JCS when using a P-384 key. We also need to ensure that we fetch the verification method early enough in the algorithm steps to get the key size to inform these decisions in implementations.

**Comment by msporny** [comment]
PR #36 has been raised to address this issue. This issue will be closed when PR #36 has been merged.

**Comment by msporny** [comment]
PR #36 has been merged, closing.
