### ISSUE TITLE
Ensure `created` proof option is optional

### ISSUE THREAD

**Issue by dlongley** [w3c/vc-di-ecdsa#47]
The current proof configuration algorithm seems to make `created` required instead of optional, this should be fixed.

**Comment by msporny** [comment]
> Or should we just repeat the language from Data Integrity for the created attribute. Note that we will want to do whatever change looks best to VC-DI-EDDSA and VC-DI-BBS since they also use this language.

Your instinct is correct, don't repeat language that exists in other specifications... instead, point to the other specification for the definitions and normative language.

**Comment by dlongley** [comment]
So PR #57 accidentally reverted the work done in #50 to ensure `created` was optional ([here](https://github.com/w3c/vc-di-ecdsa/pull/57/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R694-R697)). It should be optional in all suites.

cc: @msporny

**Comment by msporny** [comment]
> So PR #57 accidentally reverted the work done in #50 to ensure `created` was optional ([here](https://github.com/w3c/vc-di-ecdsa/pull/57/files#diff-0eb547304658805aad788d320f10bf1f292797b5e6d745a3bf617584da017051R694-R697)). It should be optional in all suites.

Thanks for catching that, the update should be an editorial fix since the right thing was committed in #50 and then accidentally undone in #57.

**Comment by Wind4Greg** [comment]
This was implemented in PR https://github.com/w3c/vc-di-ecdsa/pull/50 and has been correctly applied after the accidental reversion. See the first sentence here https://w3c.github.io/vc-di-ecdsa/#dataintegrityproof.
