### ISSUE TITLE
Ensure additional custom proof options provided via `proof` are included in the proof configuration

### ISSUE THREAD

**Issue by dlongley** [w3c/vc-di-ecdsa#48]
When creating a proof, other custom proof fields might be given, but it looks like the proof configuration algorithm will not include these -- and it should.

**Comment by Wind4Greg** [comment]
Hi @dlongley in section [Proof Configuration](https://w3c.github.io/vc-di-ecdsa/#proof-configuration-ecdsa-rdfc-2019) of the spec couldn't we change the first step: "Let proofConfig be an empty object." to "Let proofConfig be a clone of the proof options object."

Then we would remove detailed attribute assignments but keep all the checks. I also would put in a note prior to  the algorithm that other proof options are passed through. (This is where it currently states which proof options are required).

Let me know and I'll write up the PR. Note that we would also need similar changes to VC-DI-EDDSA and VC-DI-BBS.

**Comment by dlongley** [comment]
Yeah, we probably want it to be a clone as you say -- and then run the specific checks.

**Comment by dlongley** [comment]
This was my issue and it has been addressed, closing.
