### ISSUE TITLE
"Section 4: Retrieving Cryptographic Material" => "Section 4: Retrieve Verification Method"

### ISSUE THREAD

**Issue by dlongley** [w3c/vc-di-ecdsa#51]
I'll note that the current text refers to a section from vc-data-integrity as "Section 4: Retrieving Cryptographic Material" instead of "Section 4: Retrieve Verification Method" (what it is currently called in vc-di-data-integrity.

This should be editorial/informative.

**Comment by msporny** [comment]
Fixed in 1ae35b08c0e79e3c693aea545b45e7c49db670ad. Closing.
