### ISSUE TITLE
Update contexts in examples

### ISSUE THREAD

**Issue by dlongley** [w3c/vc-di-ecdsa#53]
The examples need to have their contexts checked to ensure they are up to date. At least one of them is incorrect:

Example 2:
https://w3c.github.io/vc-di-ecdsa/#example-two-public-keys-p-256-and-p-384-encoded-as-multikeys-in-a-controller-document
Should not be using context "https://w3id.org/security/data-integrity/v1" but instead: "https://w3id.org/security/multikey/v1".

**Comment by Wind4Greg** [comment]
Hmm, @dlongley  do we know where these examples came from? I've wrote the open source code for the test vectors but not for any of the examples. I could regenerate these, but if someone has the original generation code that would be quicker.

**Comment by dlongley** [comment]
I don't know where they came from, but at least for the public key examples, they shouldn't need anything regenerated, just the context adjusted.

**Comment by dlongley** [comment]
This was my issue, it was editorial, and it has been addressed, closing.
