### ISSUE TITLE
[Editorial] Making the RCH hash function reference more explicit

### ISSUE THREAD

**Issue by iherman** [w3c/vc-di-ecdsa#69]
Forgive me if I will sound very picky...

[§3. Algorithms](https://www.w3.org/TR/vc-di-ecdsa/#algorithms) contains this paragraph:

> When the RDF Dataset Canonicalization Algorithm [[RDF-CANON](https://www.w3.org/TR/vc-di-ecdsa/#bib-rdf-canon)] is used with ECDSA algorithms, the cryptographic hashing function ***that is passed to the algorithm*** MUST be determined by the size of the associated public key. For P-256 keys, SHA-2 with 256 bits of output is utilized. For P-384 keys, SHA-2 with 384-bits of output is utilized.

(Emphasis is mine).

Which is o.k., the [RDFC reference to SHA](https://www.w3.org/TR/rdf-canon/#dfn-hash-algorithm) makes it indeed possible. What it says is:

> The default hash algorithm used by [RDFC-1.0](https://www.w3.org/TR/rdf-canon/#dfn-rdfc-1-0), namely, SHA-256 [[FIPS-180-4](https://www.w3.org/TR/rdf-canon/#bib-fips-180-4)].
>
> Implementations MUST support a parameter to define the [hash algorithm](https://www.w3.org/TR/rdf-canon/#dfn-hash-algorithm), MUST support SHA-256 and SHA-384 [[FIPS-180-4](https://www.w3.org/TR/rdf-canon/#bib-fips-180-4)], and SHOULD support the ability to specify other hash algorithms.

So, if I use ecdsa with P-256, I do not "pass on" anything whatsoever, I use the default RDFC behavior. It is only when I use P-384 that I have to use the hash function parameter of RDFC (and the details on how I have to do that is implementation dependent).

Isn't it better to say something more "neutral", like

> When the RDF Dataset Canonicalization Algorithm (RDFC-1.0) [[RDF-CANON](https://www.w3.org/TR/vc-di-ecdsa/#bib-rdf-canon)] is used with ECDSA algorithms, the cryptographic hashing function used by RDFC-1.0 MUST depend on the size of the associated public key. For P-256 keys, the SHA-2 with 256 bits of output MUST be utilized, which is the default. For P-384 keys, SHA-2 with 384-bits of output MUST be utilized.

**Comment by TallTed** [comment]
I support the suggested changes, with a few minor tweaks --

> When the RDF Dataset Canonicalization Algorithm (RDFC-1.0) [[RDF-CANON](https://www.w3.org/TR/vc-di-ecdsa/#bib-rdf-canon)] is used with ECDSA algorithms, the choice of cryptographic hashing function used by RDFC-1.0 MUST be based on the size of the associated public key. For P-256 keys, SHA-2 with 256 bits of output (which is the RDFC-1.0 default) MUST be used. For P-384 keys, SHA-2 with 384-bits of output MUST be used.

It might be good to change the last bit to something like `MUST be used, by taking xyz action` that says how to not accept the default.

**Comment by iherman** [comment]
Ok @TallTed, I understand. Note however, that the `xyz` has to be intentionally vague, because it is implementation dependent.

PR follows, where the final formulation can be worked out.

**Comment by iherman** [comment]
@TallTed see #70.

This issue can be closed if and when #70 gets merged.

**Comment by msporny** [comment]
PR #70 has been merged, closing.
