### ISSUE TITLE
Different hashing functions in ECDSA and their relations to RDF-CANON

### ISSUE THREAD

**Issue by iherman** [w3c/vc-di-ecdsa#74]
Let us say we use P-384 for an ECDSA ecdsa-rdfc-2019. The specification clearly says that SHA-384 must be used to hash the transformed document in the (1) and (2) bullet points of [§ 3.2.4 Hashing](https://www.w3.org/TR/vc-di-ecdsa/#hashing-ecdsa-rdfc-2019).

Hashing is also used by the RDFC algorithm during the canonicalization process itself. Furthermore, the RDFC specification makes it a requirement for RDFC implementations to "set" the hashing functions, i.e., it would be possible at this point to instruct the RDFC process to also use SHA-384 internally. However, the reference to the transformation (i.e., [§ 3.2.3 Transformation](https://www.w3.org/TR/vc-di-ecdsa/#transformation-ecdsa-rdfc-2019)) _does not say anything about this_. As it is written, the RDFC process would use its default hashing algorithm, namely SHA-256.

The question is: is this what we want? The reason I ask is that I have heard references to the fact that the RDFC implementations should also use SHA-384 internally in this case, which is not in the spec.

To be clear: _personally, I would prefer to stick to SHA-256_. It would avoid a re-canonicalization of a graph when, for example, proof sets are used, and canonicalization could be a costly operation for a larger set.

**Comment by dlongley** [comment]
This text appears at the top of the algorithms section:

> When the RDF Dataset Canonicalization Algorithm (RDFC-1.0) [[RDF-CANON](https://www.w3.org/TR/vc-di-ecdsa/#bib-rdf-canon)] is used with ECDSA algorithms, the cryptographic hashing function used by RDFC-1.0 is chosen based on the size of the associated public key. For P-256 keys, the default hashing function, SHA-2 with 256 bits of output, MUST be used. For P-384 keys, SHA-2 with 384-bits of output MUST be used, specified via the RDFC-1.0 [implementation-specific parameter](https://www.w3.org/TR/rdf-canon/#dfn-hash-algorithm).

https://www.w3.org/TR/vc-di-ecdsa/#algorithms

We might want to say this again in the algorithm or just link back to it so we don't repeat ourselves.

> The question is: is this what we want? The reason I ask is that I have heard references to the fact that the RDFC implementations should also use SHA-384 internally in this case, which is not in the spec.
> 
> To be clear: personally, I would prefer to stick to SHA-256. It would avoid a re-canonicalization of a graph when, for example, proof sets are used, and canonicalization could be a costly operation for a larger set.

It's not what I want either, but it's what's already been implemented (in several implementations) and, from what I understand, what some people who really want to use P-384 prefer. I don't think it would be so costly to cause any significant issue, i.e., I would expect the size of a large dataset and the transfer of it would greatly outweigh any processing costs. Not everyone needs to use P-384 either.

**Comment by iherman** [comment]
> This text appears at the top of the algorithms section:
> 
> > When the RDF Dataset Canonicalization Algorithm (RDFC-1.0) [[RDF-CANON](https://www.w3.org/TR/vc-di-ecdsa/#bib-rdf-canon)] is used with ECDSA algorithms, the cryptographic hashing function used by RDFC-1.0 is chosen based on the size of the associated public key. For P-256 keys, the default hashing function, SHA-2 with 256 bits of output, MUST be used. For P-384 keys, SHA-2 with 384-bits of output MUST be used, specified via the RDFC-1.0 [implementation-specific parameter](https://www.w3.org/TR/rdf-canon/#dfn-hash-algorithm).
> 
> https://www.w3.org/TR/vc-di-ecdsa/#algorithms

Sorry, I missed this. When I asked myself the question, it did not come to my mind to look for the details of that sort of introductory section...

> 
> We might want to say this again in the appropriate subalgorithm or just link back to it so we don't repeat ourselves.

At least that. But I believe the 'subalgorithm' section is the only place where this issue is relevant, and it is a bit of a detail on the implementation. Wouldn't it be better to _move_ that remark from the general section to this place?

> 
> > The question is: is this what we want? The reason I ask is that I have heard references to the fact that the RDFC implementations should also use SHA-384 internally in this case, which is not in the spec.
> > To be clear: personally, I would prefer to stick to SHA-256. It would avoid a re-canonicalization of a graph when, for example, proof sets are used, and canonicalization could be a costly operation for a larger set.
> 
> It's not what I want either, but it's what's already been implemented (in several implementations) and, from what I understand, what some people who really want to use P-384 prefer. 

Ok. I have to accept that, I guess. 😒

> I don't think it would be so costly to cause any significant issue, i.e., I would expect the size of a large dataset and the transfer of it would greatly outweigh any processing costs. Not everyone needs to use P-384 either.

That is where I may disagree. Canonicalization may become a (very) costly operation for a large dataset, which may also involve database queries (getting the triples from a triple store, that is). On the other hand, if we have a proof set or chain, this may force the implementation to repeat c14n for the same graph.  (Anecdotal fact is that a medical ontology, in RDF form, may easily reach half a million triples...)

But I presume that is a discussion for another day and place.

**Comment by dlongley** [comment]
> At least that. But I believe the 'subalgorithm' section is the only place where this issue is relevant, and it is a bit of a detail on the implementation. Wouldn't it be better to move that remark from the general section to this place?

I'm fine with moving it to the appropriate subalgorithm -- if it needs to be repeated in multiple subalgorithms, however, it should probably just be linked to once in that intro.

**Comment by iherman** [comment]
See #77. If and then it is merged, this issue may be closed.

@dlongley I have chosen to make a reference to that introduction. There are several references to RDF-CANON in the sd algorithm which I am not familiar with, so that is the safe bet.

**Comment by iherman** [comment]
https://github.com/w3c/vc-di-ecdsa/pull/77 has been merged, closing.
