### ISSUE TITLE
Transformation should refer to canonical n-quads

### ISSUE THREAD

**Issue by iherman** [w3c/vc-di-ecdsa#75]
The [§ 3.2.3 Transformation](https://www.w3.org/TR/vc-di-ecdsa/#transformation-ecdsa-rdfc-2019) section says:

> then serializing the result to [[N-QUADS](https://www.w3.org/TR/vc-di-ecdsa/#bib-n-quads)].

The reference should, rather, be to the [§5. Serialization](https://www.w3.org/TR/rdf-canon/#serialization) format as defined in the RDFC spec. Otherwise subtle differences may occur in the output of the serialization and rdfc also states that the quads are sorted.

B.t.w., RDFC implementations are required to return such a form (see point (7) in the [Algorithm section](https://www.w3.org/TR/rdf-canon/#canon-algo-algo)) so this is really just to make the specification precise. 

eddsa has exactly the same issue. So does BBS in https://www.w3.org/TR/vc-di-bbs/#base-proof-transformation-bbs-2023, but that seems to be more complicated (and I have no familiarity with BBS to be able to offer a proper replacement)

**Comment by iherman** [comment]
cc @dlongley @msporny @BigBlueHat @Wind4Greg

**Comment by dlongley** [comment]
+1 ... I think wherever we talk about serializing to N-Quads (or to a single N-Quad) we should just change the reference to the above one.

**Comment by iherman** [comment]
I am happy to produce a PR for ecdsa and eddsa if we all agree. I would prefer not to touch the bbs spec, because I am much less familiar with it...

**Comment by msporny** [comment]
Yes, let's please get a PR raised for this @iherman!

**Comment by iherman** [comment]
> Yes, let's please get a PR raised for this @iherman!

I would prefer to do this if and when #73 is merged. Otherwise, I would run into merge conflicts...

**Comment by msporny** [comment]
> I would prefer to do this if and when #73 is merged. Otherwise, I would run into merge conflicts...

What you can do is base your modifications on top of #73, to do this:

```
git checkout iherman-RDFC-references-again
git checkout -b iherman-issue-75
```
Then make your changes
git push the branch up to here
Raise a PR and set it's "main" branch to iherman-issue-75 at the top of the screen.

... or, you could just wait for #73 to be merged.

**Comment by iherman** [comment]
> > I would prefer to do this if and when #73 is merged. Otherwise, I would run into merge conflicts...
> 
> What you can do is base your modifications on top of #73, to do this:
> 
> ```
> git checkout iherman-RDFC-references-again
> git checkout -b iherman-issue-75
> ```
> 
> Then make your changes git push the branch up to here Raise a PR and set it's "main" branch to iherman-issue-75 at the top of the screen.
> 
> ... or, you could just wait for #73 to be merged.

#73 does not seem to be a controversial PR, so it will merged quickly I guess... I will do the other pending ones first and can come back to this one.

**Comment by iherman** [comment]
I decided to do it differently. I have just raised https://github.com/w3c/vc-di-eddsa/pull/98: the required changes are indeed identical for EdDSA and ECDSA. We can finalize the text over there, and retrofit it for ECDSA afterwards. By then, maybe, #73 will be merged.

**Comment by iherman** [comment]
#77 covers this. If that is merged, this issue may be closed.

**Comment by iherman** [comment]
https://github.com/w3c/vc-di-ecdsa/pull/77 merged, closing this.
