### ISSUE TITLE
Are the unformatted JSON examples intentional?

### ISSUE THREAD

**Issue by iherman** [w3c/vc-di-ecdsa#78]
Looking at the test vector section, there are a number of JSON examples that are unformatted, e.g., [43](https://www.w3.org/TR/vc-di-ecdsa/#example-canonical-proof-options-document-2), [64](https://www.w3.org/TR/vc-di-ecdsa/#example-derived-group-indexes), or [66](https://www.w3.org/TR/vc-di-ecdsa/#example-filtered-signatures). 

Is this intentional, i.e., are these JSON structures required to be canonical (ie, no new lines or spaces)? If so they are correct but, if not, it would be nicer to format them to make those examples more understandable...

**Comment by msporny** [comment]
PR #79, which was raised to address this issue and is purely editorial, has been merged. Closing.
