### ISSUE TITLE
`urnScheme` unclear and/or missing

### ISSUE THREAD

**Issue by brianorwhatever** [w3c/vc-di-ecdsa#80]
The spec isn't clear and when I got to [`skolemizeCompactJsonLD`](https://www.w3.org/TR/vc-di-ecdsa/#skolemizecompactjsonld) I encountered I needed a `urnScheme` that wasn't an input anywhere.. Is this supposed to be a constant? `custom-scheme` perhaps?

**Comment by dlongley** [comment]
The literal string `"custom-scheme:"` (that would produce `<urn:custom-scheme:stuff>` URLs) is passed in when using this algorithm in step 3 of [`toDeskolemizedNQuads`](https://www.w3.org/TR/vc-di-ecdsa/#todeskolemizednquads):

> Set deskolemizedNQuads to the result of the algorithm in Section [3.4.6 deskolemizeNQuads](https://www.w3.org/TR/vc-di-ecdsa/#deskolemizenquads) with skolemizedNQuads and "custom-scheme:" as parameters.

Additionally this text is given:

> Implementations MAY choose a different urnScheme that is different than "custom-scheme:" so long as the same scheme name was used to generate skolemizedDocument.

So the expectation is just for the scheme to match in both places so the transform can be properly reversed. In the [`skolemizeNQuads`](https://www.w3.org/TR/vc-di-ecdsa/#skolemizenquads) algorithm, similar text referencing `"custom-scheme:"` appears:

> For example, a regular expression of a similar form to the following would achieve the desired result: s1.replace(/(_:([^\s]+))/g, '<urn:custom-scheme:$2>').

Perhaps all that is missing is clarifying text that `urnScheme` defaults to `"custom-scheme":` when not given.

**Comment by brianorwhatever** [comment]
yeah I think that clarification would help. I found the 1st quote above eventually just had to do some searching

**Comment by msporny** [comment]
PR #81 was applied to address this issue. Closing.
