### ISSUE TITLE
Why isn't `selectPaths` functional?

### ISSUE THREAD

**Issue by brianorwhatever** [w3c/vc-di-ecdsa#82]
This is the first function I've encountered that had side effects and honestly I find it hard to reason about.

Is there a reason `selectionDocument` is a parameter rather than a returned value?

**Comment by brianorwhatever** [comment]
I managed to get this function working after some fussing. it works great just seems out of place. Feel free to close this as a no op

**Comment by dlongley** [comment]
The current design allows a single selection document to be populated from many different pointers. This is done in [`selectJsonLd`](https://w3c.github.io/vc-di-ecdsa/#selectjsonld) by calling `selectPaths` multiple times on the same selection document in a loop over an array of pointers.

Perhaps this could be done a different (e.g., more functional) way, but notably, implementations are already free to vary any of the algorithms or functions however is preferred provided that the overall outputs are the same.

**Comment by brianorwhatever** [comment]
Yep closing thanks
