### ISSUE TITLE
`selectPaths` of partial object in array

### ISSUE THREAD

**Issue by brianorwhatever** [w3c/vc-di-ecdsa#83]
I believe I have implemented `selectPaths` and `selectJsonLD` correctly however I have a test failing that is supposed to select some of the elements of an object and drop the others. Here is the test:

```
const document = {
        '@context': {
          '@version': 1.1,
          'ex': 'https://example.org/vocab#',
          'credentials': 'ex:credentials'
        },
        'credentials': [
          { 'id': '1', 'type': 'A' },
          { 'id': '2', 'type': 'B' },
          { 'id': '3', 'type': 'C' }
        ]
      };

      const pointers = [
        '/credentials/0/id',
        '/credentials/0/type',
        '/credentials/2/id'
      ];
      const result = selectJsonLd(pointers, document);
  ```

and the resultant document is

```
{
    "@context": {
      "@version": 1.1,
      credentials: "ex:credentials",
      ex: "https://example.org/vocab#",
    },
    credentials: [
      {
        id: "1",
        type: "A",
      },
      {
        id: "3",
       type: "C",
      }
    ],
  }
  ```

so the array selection is working and making it dense.. however we are seeing the `type: "C"` property on the second element where I would expect to only see the `id`. I've traced it down pretty deep and in step 7 I am setting `selectedValue` properly but the selected Property already is:

```
{
  id: "3",
  type: "C",
}
```

Am I missing something?

**Comment by dlongley** [comment]
See [`createInitialSelection`](https://w3c.github.io/vc-di-ecdsa/#createinitialselection) which is called during step 5 of `selectPaths` whenever a new object in the path of a pointer is selected. The `id` (if not a blank node identifier) and `type` values are always included for objects in the path of a pointer (including the final target of the pointer).

**Comment by msporny** [comment]
It's not clear if a change to the specification is required at this point. @brianorwhatever, thoughts?

**Comment by brianorwhatever** [comment]
This was an issue in the tests I had written not understanding the functions entirely. No spec changes required.
